mod cli;
mod commands;
mod io;
mod types;
mod utils;

use anyhow::Result;
use clap::Parser;
use cli::{Cli, Command};
use commands::{
    closest, complement, coverage, extend, flank, get_fasta, intersect, merge, name_map, random,
    sample, shift, sort, subtract, window,
};

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Command::Closest {
            a,
            b,
            output,
            upstream,
            downstream,
            sorted,
        } => closest(
            a,
            b,
            output,
            upstream,
            downstream,
            sorted,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Complement {
            input,
            output,
            named,
            stream,
        } => complement(
            input,
            output,
            named,
            stream,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Coverage {
            a,
            b,
            output,
            fraction_query,
            fraction_target,
            reciprocal,
            either,
            sorted,
        } => coverage(
            a,
            b,
            output,
            fraction_query,
            fraction_target,
            reciprocal,
            either,
            sorted,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Extend {
            input,
            output,
            both,
            left,
            right,
            genome,
            input_format,
            field_format,
        } => extend(
            input,
            output,
            both,
            left,
            right,
            genome,
            input_format,
            field_format,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Flank {
            input,
            output,
            both,
            left,
            right,
            percent,
            genome,
            input_format,
            field_format,
        } => flank(
            input,
            output,
            genome,
            both,
            left,
            right,
            percent,
            input_format,
            field_format,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::GetFasta {
            bed,
            fasta,
            output,
            input_format,
        } => get_fasta(
            bed,
            &fasta,
            output,
            input_format,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Intersect {
            a,
            b,
            output,
            fraction_query,
            fraction_target,
            reciprocal,
            either,
            with_query,
            with_target,
            unique,
            inverse,
            stream,
        } => intersect(
            a,
            b,
            output,
            fraction_query,
            fraction_target,
            reciprocal,
            either,
            with_query,
            with_target,
            unique,
            inverse,
            stream,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Merge {
            input,
            output,
            sorted,
            stream,
            input_format,
            field_format,
        } => merge(
            input,
            output,
            sorted,
            stream,
            input_format,
            field_format,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::NameMap { input, output, map } => name_map(
            input,
            output,
            map,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Random {
            n_intervals,
            l_intervals,
            n_chr,
            max_chr_len,
            seed,
            output,
            genome,
            named,
            format,
        } => random(
            n_intervals,
            l_intervals,
            n_chr,
            max_chr_len,
            seed,
            output,
            genome,
            named,
            format,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Sample {
            input,
            output,
            number,
            fraction,
            seed,
            input_format,
            field_format,
        } => sample(
            input,
            output,
            number,
            fraction,
            seed,
            input_format,
            field_format,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Shift {
            input,
            output,
            genome,
            amount,
            percent,
            input_format,
            field_format,
        } => shift(
            input,
            output,
            genome,
            amount,
            percent,
            input_format,
            field_format,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Sort {
            input,
            output,
            input_format,
            field_format,
            threads,
        } => sort(
            input,
            output,
            input_format,
            field_format,
            threads,
            cli.compression_threads,
            cli.compression_level,
        )?,
        Command::Subtract {
            a,
            b,
            output,
            fraction_query,
            fraction_target,
            reciprocal,
            either,
            unmerged,
        } => {
            subtract(
                a,
                b,
                output,
                fraction_query,
                fraction_target,
                reciprocal,
                either,
                unmerged,
                cli.compression_threads,
                cli.compression_level,
            )?;
        }
        Command::Window {
            a,
            b,
            output,
            both,
            left,
            right,
            inverse,
        } => window(
            a,
            b,
            output,
            both,
            left,
            right,
            inverse,
            cli.compression_threads,
            cli.compression_level,
        )?,
    }
    Ok(())
}
